services:
  - type: web
    name: voice-sentiment-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18